In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 

fao= pd.read_csv("FAOSTAT.csv")
fao.head()
fao.describe()

       Area Code (FAO)   Element Code      Item Code     Year Code  Note
count    120698.000000  120698.000000  120698.000000  1.206980e+05   0.0
mean        129.006206    6126.148130   63623.580540  7.181792e+06   NaN
std          75.774948       9.522529   78951.034606  9.628340e+06   NaN
min           1.000000    6121.000000   21010.000000  2.000000e+03   NaN
25%          63.000000    6121.000000   21032.000000  2.007000e+03   NaN
50%         126.000000    6123.000000   21047.000000  2.015000e+03   NaN
75%         193.000000    6128.000000   22013.000000  2.005201e+07   NaN
max         351.000000    6173.000000  210490.000000  2.018202e+07   NaN

In [26]:
fao.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120698 entries, 0 to 120697
Data columns (total 15 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Domain Code       120698 non-null  object
 1   Domain            120698 non-null  object
 2   Area Code (FAO)   120698 non-null  int64
 3   Area              120698 non-null  object
 4   Element Code      120698 non-null  int64
 5   Element           120698 non-null  object
 6   Item Code         120698 non-null  int64
 7   Item              120698 non-null  object
 8   Year Code         120698 non-null  int64
 9   Year              120698 non-null  object
 10  Unit              120698 non-null  object
 11  Value             116267 non-null  object
 12  Flag              120698 non-null  object
 13  Flag Description  120698 non-null  object
 14  Note              0 non-null       float64
dtypes: float64(1), int64(4), object(10)
memory usage: 13.8+ MB

In [27]:
fao.nunique()

Domain Code            1
Domain                 1
Area Code (FAO)      204
Area                 204
Element Code          10
Element                1
Item Code             42
Item                  42
Year Code             40
Year                  40
Unit                  10
Value               8950
Flag                   4
Flag Description       4
Note                   0
dtype: int64

In [28]:
fao.columns

Index(['Domain Code', 'Domain', 'Area Code (FAO)', 'Area', 'Element Code',
       'Element', 'Item Code', 'Item', 'Year Code', 'Year', 'Unit', 'Value',
       'Flag', 'Flag Description', 'Note'],
      dtype='object')

In [29]:
fao.isnull().sum()

Domain Code              0
Domain                   0
Area Code (FAO)          0
Area                     0
Element Code             0
Element                  0
Item Code                0
Item                     0
Year Code                0
Year                     0
Unit                     0
Value                 4431
Flag                     0
Flag Description         0
Note                120698
dtype: int64

In [30]:
fao_drop=fao.drop(["Value","Note"],axis=1)
fao_drop

,Domain Code,Domain,Area Code (FAO),Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Flag,Flag Description
0,FS,Suite of Food Security Indicators,2,Afghanistan,6121,Value,21010,Average dietary energy supply adequacy (percen...,20002002,2000-2002,%,F,FAO estimate
1,FS,Suite of Food Security Indicators,2,Afghanistan,6121,Value,21010,Average dietary energy supply adequacy (percen...,20012003,2001-2003,%,F,FAO estimate
2,FS,Suite of Food Security Indicators,2,Afghanistan,6121,Value,21010,Average dietary energy supply adequacy (percen...,20022004,2002-2004,%,F,FAO estimate
3,FS,Suite of Food Security Indicators,2,Afghanistan,6121,Value,21010,Average dietary energy supply adequacy (percen...,20032005,2003-2005,%,F,FAO estimate
4,FS,Suite of Food Security Indicators,2,Afghanistan,6121,Value,21010,Average dietary energy supply adequacy (percen...,20042006,2004-2006,%,F,FAO estimate
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120693,FS,Suite of Food Security Indicators,181,Zimbabwe,6123,Value,21061,Average fat supply (g/cap/day) (3-year average),20122014,2012-2014,g/capita/day,F,FAO estimate
120694,FS,Suite of Food Security Indicators,181,Zimbabwe,6123,Value,21061,Average fat supply (g/cap/day) (3-year average),20132015,2013-2015,g/capita/day,F,FAO estimate
120695,FS,Suite of Food Security Indicators,181,Zimbabwe,6123,Value,21061,Average fat supply (g/cap/day) (3-year average),20142016,2014-2016,g/capita/day,F,FAO estimate
120696,FS,Suite of Food Security Indicators,181,Zimbabwe,6123,Value,21061,Average fat supply (g/cap/day) (3-year average),20152017,2015-2017,g/capita/day,F,FAO estimate
120697,FS,Suite of Food Security Indicators,181,Zimbabwe,6123,Value,21061,Average fat supply (g/cap/day) (3-year average),20162018,2016-2018,g/capita/day,F,FAO estimate

In [31]:
fao_drop.isnull().sum()

Domain Code         0
Domain              0
Area Code (FAO)     0
Area                0
Element Code        0
Element             0
Item Code           0
Item                0
Year Code           0
Year                0
Unit                0
Flag                0
Flag Description    0
dtype: int64

In [32]:
fao_drop.head()

,Domain Code,Domain,Area Code (FAO),Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Flag,Flag Description
0,FS,Suite of Food Security Indicators,2,Afghanistan,6121,Value,21010,Average dietary energy supply adequacy (percen...,20002002,2000-2002,%,F,FAO estimate
1,FS,Suite of Food Security Indicators,2,Afghanistan,6121,Value,21010,Average dietary energy supply adequacy (percen...,20012003,2001-2003,%,F,FAO estimate
2,FS,Suite of Food Security Indicators,2,Afghanistan,6121,Value,21010,Average dietary energy supply adequacy (percen...,20022004,2002-2004,%,F,FAO estimate
3,FS,Suite of Food Security Indicators,2,Afghanistan,6121,Value,21010,Average dietary energy supply adequacy (percen...,20032005,2003-2005,%,F,FAO estimate
4,FS,Suite of Food Security Indicators,2,Afghanistan,6121,Value,21010,Average dietary energy supply adequacy (percen...,20042006,2004-2006,%,F,FAO estimate

In [35]:
fao_drop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120698 entries, 0 to 120697
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Domain Code       120698 non-null  object
 1   Domain            120698 non-null  object
 2   Area Code (FAO)   120698 non-null  int64
 3   Area              120698 non-null  object
 4   Element Code      120698 non-null  int64
 5   Element           120698 non-null  object
 6   Item Code         120698 non-null  int64
 7   Item              120698 non-null  object
 8   Year Code         120698 non-null  int64
 9   Year              120698 non-null  object
 10  Unit              120698 non-null  object
 11  Flag              120698 non-null  object
 12  Flag Description  120698 non-null  object
dtypes: int64(4), object(9)
memory usage: 12.0+ MB

In [36]:
fao_drop.shape

(120698, 13)

In [39]:
fao.shape

(120698, 15)